spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: emsdb-local
  application:
    name: ems
  jackson:
    serialization:
      fail-on-empty-beans: false
#  security:
#    user:
#      password: aliassad
#      name: ali
  jpa:
    open-in-view: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      #      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      #      hibernate.enable_lazy_load_no_trans: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ems_with_keycloak?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  main:
    allow-circular-references: true

    allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true
  cache:
    type: redis

  redis:
    port: 6379
    host: localhost
#  elasticsearch:
#    uris: http://localhost:9200
server:
  port: 8181

logging:
  level:
    com.ems.EmployeeManagementService: Debug

jwt_secret : tabadul
jwtExpirationMs: 120000
refreshTokenDurationMs: 1200000
management:
  health:
    elasticsearch:
      enabled: false


keycloak:
  realm: master
  resource: ems
  auth-server-url: http://localhost:9080/auth
  ssl-required: external
  principal-attribute: preferred_username
  credentials:
    secret: 5e41f1bb-1434-4b44-8699-1b5a4a38bde2

#  use-resource-role-mappings: true
#  bearer-only: true